### ISSUE TITLE
Create a To-Do App

### ISSUE THREAD

**Issue by HARSHITHA-SC23** [HARSHITHA-SC23/JSBeginners#1]
The user should be able to

- [x] See visually appealing UI
- [x] Create new tasks 
- [x] The new tasks should have a deadline and priority.
- [x] Delete all the tasks.
- [x] User should able to scratch the completed task

Optional

- [x] View the tasks in different views (Visual appearance based on priority)
